---
- hosts: droplet
  become: yes
  tasks:
    - name: Create directory named "final project"
      file:
        path: /home/{{ ansible_user }}/final_project
        state: directory

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Clone the repository
      git:
        repo: 'https://github.com/Ahmed3019/my-cv-application'
        dest: /home/{{ ansible_user }}/final_project/my-cv-application

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Minikube
      apt:
        name: minikube
        state: present
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Pull the Docker image
      docker_image:
        name: ahmedsalama3014/frontend-task
        source: pull

    - name: Run Docker container on port 80
      docker_container:
        name: frontend-task
        image: ahmedsalama3014/frontend-task
        state: started
        ports:
          - "80:80"
